---
name: Weekly Sync with Upstream

on:
  schedule:
    - cron: "0 3 * * 0"  # Every Sunday at 3AM UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: festion/component-ab-gateway
          token: ${{ secrets.GH_TOKEN_ADMIN_AB_GATEWAY }}

      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "bot@users.noreply.github.com"
          git remote add upstream https://github.com/AprilBrother/component-ab-gateway.git
          git fetch upstream
          git merge --ff-only upstream/main || \
            echo "⚠️ Merge failed or not fast-forward."
          git push origin main
